name: radio_allam
description: A Flutter podcast app
publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5  # لإدارة الحالة والانتقالات
  just_audio: ^0.9.18  # لتشغيل البث المباشر
  cached_network_image: ^3.2.0  # لعرض الصور من الشبكة
  shared_preferences: ^2.0.9  # لتخزين البيانات المحلية
  flutter_svg: ^1.0.3  # لدعم الصور بصيغة SVG
  animate_do: ^2.0.0  # مكتبة رسوم متحركة
  google_fonts: ^3.0.1  # لاستخدام خطوط حديثة
  audio_service: ^0.18.2
  get_storage: ^2.0.3
  path_provider: ^2.0.9
  permission_handler: ^10.2.0
flutter:
  assets:
    - assets/Audio/radio.mp3
    - assets/images/quran.png
    - assets/images/khuzama.png
    - assets/images/logo.png
    - assets/images/Live1.png
    - assets/images/Live2.png
    - assets/images/Live3.png
    - assets/images/p1.png
    - assets/images/p2.png
    - assets/images/p3.png
    - assets/images/p4.png
    - assets/images/p5.png
    - assets/icons/Play.png
  uses-material-design: true